In [2]:
import pandas as pd
import numpy as np


grid=pd.read_csv('gridWeather1704-1706.csv',index_col=0)
grid.info()
grid.head()

/anaconda3/lib/python3.6/site-packages/numpy/lib/arraysetops.py:522: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1421784 entries, 1406160 to 2827943
Data columns (total 9 columns):
stationName       1421784 non-null object
longitude         1421784 non-null float64
latitude          1421784 non-null float64
utc_time          1421784 non-null object
temperature       1421784 non-null float64
pressure          1421784 non-null float64
humidity          1421784 non-null float64
wind_direction    1421784 non-null float64
wind_speed/kph    1421784 non-null float64
dtypes: float64(7), object(2)
memory usage: 108.5+ MB

,stationName,longitude,latitude,utc_time,temperature,pressure,humidity,wind_direction,wind_speed/kph
1406160,beijing_grid_000,115.0,39.0,2017-04-01 00:00:00,10.55,980.06,28.80,307.92,12.59
1406161,beijing_grid_001,115.0,39.1,2017-04-01 00:00:00,10.31,974.89,28.83,307.06,12.61
1406162,beijing_grid_002,115.0,39.2,2017-04-01 00:00:00,9.58,959.35,28.91,304.48,12.65
1406163,beijing_grid_003,115.0,39.3,2017-04-01 00:00:00,8.85,943.82,29.00,301.94,12.73
1406164,beijing_grid_004,115.0,39.4,2017-04-01 00:00:00,7.65,926.03,30.24,305.52,13.15

In [3]:
#drop duplicate
grid=grid.drop_duplicates()
len(grid)

1421784

In [4]:
#total amount of distinct time
total_distime=grid.utc_time.unique()

len(total_distime)

2184

In [5]:
#total time for each station, check missing hrs
my_list=grid.groupby('stationName')['utc_time'].apply(list)

my_df = pd.DataFrame(my_list)

time=my_df['utc_time']

#len(time[0])
#my_df.info
for i in range(len(my_list)):
    print(len(my_list[i]))
    #len(my_list[i])

2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184
2184

In [6]:
grid['wind_speed']=grid['wind_speed/kph']*5/18

In [7]:
grid=grid.drop('wind_speed/kph',axis=1)
grid.head()

,stationName,longitude,latitude,utc_time,temperature,pressure,humidity,wind_direction,wind_speed
1406160,beijing_grid_000,115.0,39.0,2017-04-01 00:00:00,10.55,980.06,28.80,307.92,3.497222
1406161,beijing_grid_001,115.0,39.1,2017-04-01 00:00:00,10.31,974.89,28.83,307.06,3.502778
1406162,beijing_grid_002,115.0,39.2,2017-04-01 00:00:00,9.58,959.35,28.91,304.48,3.513889
1406163,beijing_grid_003,115.0,39.3,2017-04-01 00:00:00,8.85,943.82,29.00,301.94,3.536111
1406164,beijing_grid_004,115.0,39.4,2017-04-01 00:00:00,7.65,926.03,30.24,305.52,3.652778

In [8]:
#check total amount of wind_speed <0.5
count=0
for i, ele in enumerate(grid['wind_speed']):
    if ele<0.5:
       # print(i,ele)
         count=count+1
        
count

26945

In [9]:
#when wind_speed<0.5,change the corresponding wind_direction to 999017
grid.loc[grid['wind_speed']<0.5, 'wind_direction'] =0

In [10]:
grid[9000:12000]

,stationName,longitude,latitude,utc_time,temperature,pressure,humidity,wind_direction,wind_speed
1415160,beijing_grid_537,117.5,40.2,2017-04-01 13:00:00,10.90,969.28,34.39,134.26,2.761111
1415161,beijing_grid_538,117.5,40.3,2017-04-01 13:00:00,10.09,951.47,35.24,140.51,2.488889
1415162,beijing_grid_539,117.5,40.4,2017-04-01 13:00:00,9.14,934.93,36.20,147.38,2.261111
1415163,beijing_grid_540,117.5,40.5,2017-04-01 13:00:00,8.50,923.43,36.76,151.61,2.075000
1415164,beijing_grid_541,117.5,40.6,2017-04-01 13:00:00,8.47,922.00,36.50,147.87,1.911111
1415165,beijing_grid_542,117.5,40.7,2017-04-01 13:00:00,8.44,920.57,36.24,143.46,1.761111
1415166,beijing_grid_543,117.5,40.8,2017-04-01 13:00:00,9.05,933.16,35.69,130.78,1.811111
1415167,beijing_grid_544,117.5,40.9,2017-04-01 13:00:00,9.65,945.75,35.14,119.33,1.944444
1415168,beijing_grid_545,117.5,41.0,2017-04-01 13:00:00,9.85,949.94,34.96,115.90,2.002778
1415169,beijing_grid_546,117.6,39.0,2017-04-01 13:00:00,10.16,1015.81,52.04,140.07,5.947222
1415170,beijing_grid_547,117.6,39.1,2017-04-01 13:00:00,10.18,1015.78,50.57,140.13,5.797222
1415171,beijing_grid_548,117.6,39.2,2017-04-01 13:00:00,10.25,1015.68,46.16,140.34,5.347222
1415172,beijing_grid_549,117.6,39.3,2017-04-01 13:00:00,10.32,1015.58,41.75,140.59,4.897222
1415173,beijing_grid_550,117.6,39.4,2017-04-01 13:00:00,10.28,1015.57,39.89,139.51,4.550000
1415174,beijing_grid_551,117.6,39.5,2017-04-01 13:00:00,10.23,1015.56,38.03,138.25,4.205556
1415175,beijing_grid_552,117.6,39.6,2017-04-01 13:00:00,10.22,1015.66,36.84,135.49,3.875000
1415176,beijing_grid_553,117.6,39.7,2017-04-01 13:00:00,10.22,1015.83,35.98,131.55,3.561111
1415177,beijing_grid_554,117.6,39.8,2017-04-01 13:00:00,10.45,1015.02,35.06,128.33,3.338889
1415178,beijing_grid_555,117.6,39.9,2017-04-01 13:00:00,11.14,1012.28,34.01,127.72,3.263889
1415179,beijing_grid_556,117.6,40.0,2017-04-01 13:00:00,11.84,1009.53,32.95,127.07,3.188889
1415180,beijing_grid_557,117.6,40.1,2017-04-01 13:00:00,11.59,994.42,33.13,132.54,2.955556
1415181,beijing_grid_558,117.6,40.2,2017-04-01 13:00:00,11.34,979.31,33.31,138.87,2.752778
1415182,beijing_grid_559,117.6,40.3,2017-04-01 13:00:00,10.59,962.25,34.14,143.74,2.544444
1415183,beijing_grid_560,117.6,40.4,2017-04-01 13:00:00,9.58,944.22,35.30,148.19,2.330556
1415184,beijing_grid_561,117.6,40.5,2017-04-01 13:00:00,8.90,931.68,35.98,150.23,2.136111
1415185,beijing_grid_562,117.6,40.6,2017-04-01 13:00:00,8.88,930.11,35.68,145.57,1.955556
1415186,beijing_grid_563,117.6,40.7,2017-04-01 13:00:00,8.86,928.54,35.39,140.00,1.791667
1415187,beijing_grid_564,117.6,40.8,2017-04-01 13:00:00,9.35,939.21,34.76,128.18,1.788889
1415188,beijing_grid_565,117.6,40.9,2017-04-01 13:00:00,9.84,949.88,34.13,116.80,1.858333
1415189,beijing_grid_566,117.6,41.0,2017-04-01 13:00:00,10.01,953.44,33.92,113.25,1.897222
...,...,...,...,...,...,...,...,...,...
1418130,beijing_grid_252,116.2,39.0,2017-04-01 18:00:00,9.05,1016.56,37.04,82.94,2.611111
1418131,beijing_grid_253,116.2,39.1,2017-04-01 18:00:00,9.00,1016.52,37.50,79.50,2.647222
1418132,beijing_grid_254,116.2,39.2,2017-04-01 18:00:00,8.86,1016.39,38.88,69.87,2.808333
1418133,beijing_grid_255,116.2,39.3,2017-04-01 18:00:00,8.72,1016.26,40.25,61.48,3.036111
1418134,beijing_grid_256,116.2,39.4,2017-04-01 18:00:00,8.66,1015.66,41.15,57.94,3.008333
1418135,beijing_grid_257,116.2,39.5,2017-04-01 18:00:00,8.60,1015.05,42.05,54.35,2.994444
1418136,beijing_grid_258,116.2,39.6,2017-04-01 18:00:00,8.37,1013.76,42.77,52.73,2.755556
1418137,beijing_grid_259,116.2,39.7,2017-04-01 18:00:00,8.06,1012.12,43.40,51.96,2.405556
1418138,beijing_grid_260,116.2,39.8,2017-04-01 18:00:00,7.62,1009.01,44.39,53.68,2.002778
1418139,beijing_grid_261,116.2,39.9,2017-04-01 18:00:00,6.93,1002.95,46.06,63.89,1.527778
1418140,beijing_grid_262,116.2,40.0,2017-04-01 18:00:00,6.24,996.89,47.74,82.04,1.138889
1418141,beijing_grid_263,116.2,40.1,2017-04-01 18:00:00,6.14,992.96,47.06,93.82,1.122222
1418142,beijing_grid_264,116.2,40.2,2017-04-01 18:00:00,6.04,989.04,46.39,105.44,1.155556
1418143,beijing_grid_265,116.2,40.3,2017-04-01 18:00:00,5.27,973.14,47.33,113.88,0.986111
1418144,beijing_grid_266,116.2,40.4,2017-04-01 18:00:00,4.15,951.26,49.07,125.58,0.722222
1418145,beijing_grid_267,116.2,40.5,2017-04-01 18:00:00,3.35,934.31,49.62,0.00,0.469444
1418146,beijing_grid_268,116.2,40.6,2017-04-01 18:00:00,3.16,927.20,47.78,0.00,0.438889
1418147,beijing_grid_269,116.2,40.7,2017-04-01 18:00:00,2.97,920.10,45.93,247.70,0.788889
1418148,beijing_grid_270,116.2,40.8,2017-04-01 18:00:00,2.91,907.18,44.57,295.43,0.808333
1418149,beijing_grid_271,116.2,40.9,2017-04-01 18:00:00,2.86,894.26,43.21,323.69,1.233333
1418150,beijing_grid_272,116.2,41.0,2017-04-01 18:00:00,2.84,889.96,42.76,328.87,1.413889
1418151,beijing_grid_273,116.3,39.0,2017-04-01 18:00:00,9.07,1016.53,36.64,94.11,2.622222
1418152,beijing_grid_274,116.3,39.1,2017-04-01 18:00:00,9.02,1016.52,37.14,90.24,2.619444
1418153,beijing_grid_275,116.3,39.2,2017-04-01 18:00:00,8.89,1016.50,38.64,78.81,2.683333
1418154,beijing_grid_276,116.3,39.3,2017-04-01 18:00:00,8.75,1016.47,40.15,68.29,2.844444
1418155,beijing_grid_277,116.3,39.4,2017-04-01 18:00:00,8.61,1015.69,41.51,63.61,2.855556
1418156,beijing_grid_278,116.3,39.5,2017-04-01 18:00:00,8.47,1014.90,42.87,59.01,2.886111
1418157,beijing_grid_279,116.3,39.6,2017-04-01 18:00:00,8.27,1014.77,43.76,57.71,2.733333
1418158,beijing_grid_280,116.3,39.7,2017-04-01 18:00:00,8.06,1014.97,44.42,58.07,2.483333
1418159,beijing_grid_281,116.3,39.8,2017-04-01 18:00:00,7.75,1014.23,45.28,61.00,2.152778

In [11]:
#check if all the corresponding wind_direction has been replaced
count=0
for i, ele in enumerate(grid['wind_direction']):
    if ele==999017:
       # print(i,ele)
         count=count+1
        
count

0

In [12]:
grid.to_csv('complete_grid46.csv',index=False)

# observationweather

In [13]:

ob=pd.read_csv('observedWeather1704-1706.csv',index_col=0)
ob.info()
ob.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 39311 entries, 1448 to 152897
Data columns (total 10 columns):
station_id        39311 non-null object
longitude         39311 non-null float64
latitude          39311 non-null float64
utc_time          39311 non-null object
temperature       39311 non-null float64
pressure          39311 non-null float64
humidity          39311 non-null int64
wind_direction    39311 non-null float64
wind_speed        39311 non-null float64
weather           39311 non-null object
dtypes: float64(6), int64(1), object(3)
memory usage: 3.3+ MB

,station_id,longitude,latitude,utc_time,temperature,pressure,humidity,wind_direction,wind_speed,weather
1448,shunyi_meo,116.615278,40.126667,2017-04-01 00:00:00,10.7,1015.8,32,342.0,0.8,Sunny/clear
1449,shunyi_meo,116.615278,40.126667,2017-04-01 01:00:00,13.5,1015.7,22,6.0,1.8,Sunny/clear
1450,shunyi_meo,116.615278,40.126667,2017-04-01 02:00:00,16.2,1015.1,17,359.0,1.0,Sunny/clear
1451,shunyi_meo,116.615278,40.126667,2017-04-01 03:00:00,19.0,1014.0,14,159.0,1.2,Sunny/clear
1452,shunyi_meo,116.615278,40.126667,2017-04-01 04:00:00,18.9,1013.1,14,230.0,1.5,Sunny/clear

In [14]:
#drop duplicate
ob=ob.drop_duplicates()
len(ob)

39311

In [15]:
#total amount of distinct time
total_distime=ob.utc_time.unique()

len(total_distime)

2184

In [16]:
total_stations=ob.station_id.unique().tolist()
total_stations

['shunyi_meo',
 'hadian_meo',
 'yanqing_meo',
 'miyun_meo',
 'huairou_meo',
 'shangdianzi_meo',
 'pinggu_meo',
 'tongzhou_meo',
 'chaoyang_meo',
 'pingchang_meo',
 'zhaitang_meo',
 'mentougou_meo',
 'beijing_meo',
 'shijingshan_meo',
 'fengtai_meo',
 'daxing_meo',
 'fangshan_meo',
 'xiayunling_meo']

In [17]:
#total time for each station, check missing hrs: one missing hour
my_list=ob.groupby('station_id')['utc_time'].apply(list)

my_df = pd.DataFrame(my_list)

time=my_df['utc_time']

#len(time[0])
#my_df.info
for i in range(len(my_list)):
    #print(len(my_list[i]))
    len(my_list[i])

my_df

                                                          utc_time
station_id
beijing_meo      [2017-04-01 00:00:00, 2017-04-01 01:00:00, 201...
chaoyang_meo     [2017-04-01 00:00:00, 2017-04-01 01:00:00, 201...
daxing_meo       [2017-04-01 00:00:00, 2017-04-01 01:00:00, 201...
fangshan_meo     [2017-04-01 00:00:00, 2017-04-01 01:00:00, 201...
fengtai_meo      [2017-04-01 00:00:00, 2017-04-01 01:00:00, 201...
hadian_meo       [2017-04-01 00:00:00, 2017-04-01 01:00:00, 201...
huairou_meo      [2017-04-01 00:00:00, 2017-04-01 01:00:00, 201...
mentougou_meo    [2017-04-01 00:00:00, 2017-04-01 01:00:00, 201...
miyun_meo        [2017-04-01 00:00:00, 2017-04-01 01:00:00, 201...
pingchang_meo    [2017-04-01 00:00:00, 2017-04-01 01:00:00, 201...
pinggu_meo       [2017-04-01 00:00:00, 2017-04-01 01:00:00, 201...
shangdianzi_meo  [2017-04-01 00:00:00, 2017-04-01 01:00:00, 201...
shijingshan_meo  [2017-04-01 00:00:00, 2017-04-01 01:00:00, 201...
shunyi_meo       [2017-04-01 00:00:00, 2017-04-01 01:00:00, 201...
tongzhou_meo     [2017-04-01 00:00:00, 2017-04-01 01:00:00, 201...
xiayunling_meo   [2017-04-01 00:00:00, 2017-04-01 01:00:00, 201...
yanqing_meo      [2017-04-01 00:00:00, 2017-04-01 01:00:00, 201...
zhaitang_meo     [2017-04-01 00:00:00, 2017-04-01 01:00:00, 201...

In [18]:
#check missing hours
missing_hrs=[]
difference=[]
for i in range(len(time)):
    #print(i)
    difference.extend([i,set(total_distime)-set(time[i])])
   # d= list(set(total_distime)-set(time[i]))
#     if d:
#          missing_hrs=missing_hrs+d
        
                        
#missing_hrs
difference
#ob['station_id'][0]

[0,
 {'2017-04-17 03:00:00'},
 1,
 set(),
 2,
 set(),
 3,
 set(),
 4,
 set(),
 5,
 set(),
 6,
 set(),
 7,
 set(),
 8,
 set(),
 9,
 set(),
 10,
 set(),
 11,
 set(),
 12,
 set(),
 13,
 set(),
 14,
 set(),
 15,
 set(),
 16,
 set(),
 17,
 set()]

In [19]:
#all the stations have '2017-04-17 03:00:00'
check=ob.loc[ob['utc_time']=='2017-04-17 03:00:00']
missingsta=check['station_id'].tolist()
check

,station_id,longitude,latitude,utc_time,temperature,pressure,humidity,wind_direction,wind_speed,weather
1835,shunyi_meo,116.615278,40.126667,2017-04-17 03:00:00,23.3,997.1,27,257.0,2.3,Haze
10615,hadian_meo,116.290556,39.986944,2017-04-17 03:00:00,23.5,995.0,38,178.0,1.4,Haze
19396,yanqing_meo,115.968889,40.449444,2017-04-17 03:00:00,20.8,944.5,19,227.0,4.4,Sunny/clear
28177,miyun_meo,116.864167,40.377500,2017-04-17 03:00:00,21.5,992.1,39,240.0,1.2,Haze
36957,huairou_meo,116.626944,40.357778,2017-04-17 03:00:00,21.2,991.6,48,181.0,2.0,Haze
45738,shangdianzi_meo,117.111667,40.658889,2017-04-17 03:00:00,21.9,966.2,40,177.0,2.0,Haze
54518,pinggu_meo,117.117778,40.169444,2017-04-17 03:00:00,21.9,996.6,45,246.0,1.8,Haze
63297,tongzhou_meo,116.756667,39.847500,2017-04-17 03:00:00,21.7,998.4,49,170.0,2.1,Haze
72078,chaoyang_meo,116.500833,39.952500,2017-04-17 03:00:00,23.1,996.6,42,245.0,1.4,Haze
80859,pingchang_meo,116.211667,40.223333,2017-04-17 03:00:00,23.5,991.5,29,155.0,1.6,Haze
89640,zhaitang_meo,115.692222,39.973889,2017-04-17 03:00:00,23.4,949.8,14,133.0,1.5,Sunny/clear
98421,mentougou_meo,116.156389,39.887778,2017-04-17 03:00:00,21.1,990.9,46,151.0,3.3,Haze
115979,shijingshan_meo,116.205278,39.942500,2017-04-17 03:00:00,21.9,993.1,40,193.0,3.2,Haze
124759,fengtai_meo,116.245278,39.870278,2017-04-17 03:00:00,21.6,994.4,47,222.0,1.4,Haze
133540,daxing_meo,116.354444,39.718611,2017-04-17 03:00:00,21.0,996.4,49,198.0,2.4,Haze
142321,fangshan_meo,116.194167,39.773056,2017-04-17 03:00:00,19.8,995.2,54,206.0,2.1,Haze
151101,xiayunling_meo,115.740556,39.728611,2017-04-17 03:00:00,23.2,953.4,14,145.0,4.3,Sunny/clear

In [20]:
#missing station
found=set(total_stations)-set(missingsta)
found

{'beijing_meo'}

In [21]:
#index of missing hr 
missinghr_index=ob[(ob['utc_time']=='2017-04-17 02:00:00')&(ob['station_id']=='beijing_meo')].index.tolist()
missinghr_index

[107198]

In [22]:
ob[26590:26599]

,station_id,longitude,latitude,utc_time,temperature,pressure,humidity,wind_direction,wind_speed,weather
107194,beijing_meo,116.469444,39.806111,2017-04-16 22:00:00,11.1,1000.0,89,184.0,0.8,Haze
107195,beijing_meo,116.469444,39.806111,2017-04-16 23:00:00,13.7,1000.1,81,134.0,0.9,Haze
107196,beijing_meo,116.469444,39.806111,2017-04-17 00:00:00,999999.0,999999.0,999999,999999.0,999999.0,Sunny/clear
107197,beijing_meo,116.469444,39.806111,2017-04-17 01:00:00,18.1,998.8,62,224.0,1.8,Haze
107198,beijing_meo,116.469444,39.806111,2017-04-17 02:00:00,20.6,997.9,55,198.0,1.7,Haze
107199,beijing_meo,116.469444,39.806111,2017-04-17 04:00:00,21.5,996.1,49,210.0,2.5,Haze
107200,beijing_meo,116.469444,39.806111,2017-04-17 05:00:00,22.0,994.7,40,210.0,2.7,Haze
107201,beijing_meo,116.469444,39.806111,2017-04-17 06:00:00,24.5,993.5,32,208.0,3.3,Haze
107202,beijing_meo,116.469444,39.806111,2017-04-17 07:00:00,24.7,992.6,29,220.0,3.8,Haze

In [23]:
#check 999999
count=0
for i, ele in enumerate(ob['wind_direction']):
    if ele==999999.:
       # print(i,ele)
         count=count+1
        
count

1

In [24]:
ob.loc[[107196]]=('beijing_meo',116.469444,39.806111,'2017-04-17 00:00:00',13.7,1000.1,81,134.0,0.9,'Haze')

In [25]:
ob[26590:26599]

,station_id,longitude,latitude,utc_time,temperature,pressure,humidity,wind_direction,wind_speed,weather
107194,beijing_meo,116.469444,39.806111,2017-04-16 22:00:00,11.1,1000.0,89,184.0,0.8,Haze
107195,beijing_meo,116.469444,39.806111,2017-04-16 23:00:00,13.7,1000.1,81,134.0,0.9,Haze
107196,beijing_meo,116.469444,39.806111,2017-04-17 00:00:00,13.7,1000.1,81,134.0,0.9,Haze
107197,beijing_meo,116.469444,39.806111,2017-04-17 01:00:00,18.1,998.8,62,224.0,1.8,Haze
107198,beijing_meo,116.469444,39.806111,2017-04-17 02:00:00,20.6,997.9,55,198.0,1.7,Haze
107199,beijing_meo,116.469444,39.806111,2017-04-17 04:00:00,21.5,996.1,49,210.0,2.5,Haze
107200,beijing_meo,116.469444,39.806111,2017-04-17 05:00:00,22.0,994.7,40,210.0,2.7,Haze
107201,beijing_meo,116.469444,39.806111,2017-04-17 06:00:00,24.5,993.5,32,208.0,3.3,Haze
107202,beijing_meo,116.469444,39.806111,2017-04-17 07:00:00,24.7,992.6,29,220.0,3.8,Haze

In [26]:
#append the missing hr
line = pd.DataFrame({'station_id':'beijing_meo','longitude':116.469444,'latitude':39.806111, 'utc_time':'2017-04-17 03:00:00', 'temperature':20.6, 'pressure':997.9,'humidity':55, 'wind_direction':198.0,'wind_speed':1.7}, index=[107199])

In [27]:

ob2 = pd.concat([ob.ix[:107198], line, ob.ix[107199:]]).reset_index(drop=True)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

In [173]:
#check total amount of wind_speed <0.5
count=0
for i, ele in enumerate(ob['wind_speed']):
    if ele<0.5:
       # print(i,ele)
         count=count+1
        
count

1912

In [28]:
#when wind_speed<0.5,change the corresponding wind_direction to 999017
ob.loc[ob['wind_speed']<0.5, 'wind_direction'] =0

In [29]:
#check if all the corresponding wind_direction has been replaced
count=0
for i, ele in enumerate(ob['wind_direction']):
    if ele==999017:
       # print(i,ele)
         count=count+1
        
count

0

In [30]:
ob2[26590:26599]

,humidity,latitude,longitude,pressure,station_id,temperature,utc_time,weather,wind_direction,wind_speed
26590,89,39.806111,116.469444,1000.0,beijing_meo,11.1,2017-04-16 22:00:00,Haze,184.0,0.8
26591,81,39.806111,116.469444,1000.1,beijing_meo,13.7,2017-04-16 23:00:00,Haze,134.0,0.9
26592,81,39.806111,116.469444,1000.1,beijing_meo,13.7,2017-04-17 00:00:00,Haze,134.0,0.9
26593,62,39.806111,116.469444,998.8,beijing_meo,18.1,2017-04-17 01:00:00,Haze,224.0,1.8
26594,55,39.806111,116.469444,997.9,beijing_meo,20.6,2017-04-17 02:00:00,Haze,198.0,1.7
26595,55,39.806111,116.469444,997.9,beijing_meo,20.6,2017-04-17 03:00:00,NaN,198.0,1.7
26596,49,39.806111,116.469444,996.1,beijing_meo,21.5,2017-04-17 04:00:00,Haze,210.0,2.5
26597,40,39.806111,116.469444,994.7,beijing_meo,22.0,2017-04-17 05:00:00,Haze,210.0,2.7
26598,32,39.806111,116.469444,993.5,beijing_meo,24.5,2017-04-17 06:00:00,Haze,208.0,3.3

In [31]:
ob2.to_csv('complete_ob46.csv',index=False)